variables: {X: 10, Y: 20, Z: 30, name: Saurav}
pool: Mera Pool
stages:
- stage: Stage1
  jobs:
  - job: Job1
    steps:
    - powershell: echo $(name)
    - powershell: echo $(X), $(Y)
    - powershell: echo $(X) ` $(Z)
    - powershell: echo $(x) | $(Y)

