

  
pool: Mera Pool
stages:
- stage: Stage1
  jobs:
  - job: Job1
    variables:
    - name: X
      value: 10
    steps:
    - powershell: echo $(X)
    # - powershell: echo $(X), $(Y)
    # - powershell: echo $(X) ` $(Z)
    # - powershell: echo $(x) | $(Y)

