apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
    spec:
      containers:
      - name: add-task
        env:
          - name: CONNECTION_STRING
            value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sauravsql-dev-007.database.windows.net,1433;Database=sauravdb-dev007;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
        image: add-task
        ports:
        - containerPort: 8000
